file_format: "1"
id: skipkount
name: SkipKount
type: shield
url: https://github.com/elvit/zmk-config-xiao_numpad
description: Bluetooth wireless skipping counter
requires:
  - seeeduino_xiao_ble
features:
  - keys
  - encoder
outputs:
  - usb
  - ble